src/order_app/urls.py
from django.urls import path
from . import views


app_name = "order_app"

urlpatterns = [
    path("ajouts-produit/<int:products_id>/au_panier", views.ajouter_au_panier, name="ajouter-au-panier"),
    path("mes-articles/", views.voir_panier, name="voir-panier"),
    path("modifier-article/<int:article_id>/", views.modifier_panier, name="modifier-article"),
    path("supprimer-article/<int:article_id>/", views.supprimer_article, name="supprimer-article"),
    path("detail-commande/<int:commande_id>/", views.detail_commande, name="detail-commande"),
    path("valide-commande/", views.valide_commande, name="valide-commande"),
    path("historique-commande/", views.historique_commandes, name="historique-commande")
    
]

src/product_app/urls.py
from django.urls import path
from . import views

app_name = "product_app"

urlpatterns = [
    path("produits/",views.product_list, name="products-list"),
    path("detail/<int:product_pk>/product/", views.product_detail, name="product-detail"),
    path("recherche", views.product_search, name="search")
         ] 

src/ssm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home_app.urls")),
    path("", include("auth_app.urls")),
    path("", include("product_app.urls")),
    path ("", include("order_app.urls")),
    path("", include("payement_app.urls"))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/product_templates/product_detail.html
<!-- EN HAUT du template -->
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}


<p>{{ product_detail.name }}</p>
<p>{{ product_detail.price }}</p>
<p>{{ product_detail.stock }}</p>
<p>{{ product_detail.description }}</p>
<img src="{{product_detail.image.url}}"  width="150" alt="image">

<a href="{% url 'order_app:ajouter-au-panier' product_detail.id %}">Ajouter au panier</a>

src/templates/product_templates/product_list.html
<!-- EN HAUT du template -->
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

<input 
type="search" 
name="search" 
hx-get="{% url 'product_app:search' %}"
hx-trigger="keyup changed delay:500ms"
hx-target="#prod_li"
>

<ul>
    {% for product in products_by_page %}

    <li id="prod_li">
        <h3>{{product.name}}</h3>
        <em>{{product.price}}</em>
        <b>{{product.stock}}</b>
        <a href="{% url 'product_app:product-detail' product.id  %}">Description</a>

    </li>
    
    {% endfor %}
    
</ul>

<div>
 {% if products_by_page.has_previous %}
    <a href="?page={{products_by_page.previous_page_number}}">arrière_page</a>
    {% endif %}
    <span> {{ poducts_by_page.number}}</span>  
    
    
    {% if products_by_page.has_next %}
        <a href="?page={{ products_by_page.next_page_number}}">next_page</a>
    {% endif %}
         
</div>
    
   
    