src/order_app/urls.py
from django.urls import path
from . import views


app_name = "order_app"

urlpatterns = [
    path("ajouts-produit/<int:products_id>/au_panier", views.ajouter_au_panier, name="ajouter-au-panier"),
    path("mes-articles/", views.voir_panier, name="voir-panier"),
    path("modifier-article/<int:article_id>/", views.modifier_panier, name="modifier-article"),
    path("supprimer-article/<int:article_id>/", views.supprimer_article, name="supprimer-article"),
    path("detail-commande/<int:commande_id>/", views.detail_commande, name="detail-commande"),
    path("valide-commande/", views.valide_commande, name="valide-commande"),
    path("historique-commande/", views.historique_commandes, name="historique-commande")
    
]

src/payement_app/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = "payement_app"

urlpatterns = [
    path("choix-paiement/<int:commande_id>/", views.choix_paiement, name="choix-paiement"),
    path("paiement-ligdicash/<int:commande_id>/<str:type_paiement>", views.initier_paiement_ligdicash, name="paiement-ligdicash"),
    path('webhook/ligdicash/', webhooks.webhook_ligdicash, name='webhook_ligdicash')

]    

src/ssm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home_app.urls")),
    path("", include("auth_app.urls")),
    path("", include("product_app.urls")),
    path ("", include("order_app.urls")),
    path("", include("payement_app.urls"))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/order_templates/detail_commande.html
  


<h1>📋 Détails de la Commande #{{ commande_detail.id }}</h1>

<div class="commande-info">
    <p><strong>Statut :</strong> {{ commande_detail.statut }}</p>
    <p><strong>Date :</strong> {{ commande_detail.date_commande }}</p>
    <p><strong>Panier lié :</strong> {{ commande_detail.panier.id }}</p>
</div>

<h2>Articles dans cette commande :</h2>
<ul>
{% for article in panier.articlepanier_set.all %}
    <li>
        {{ article.product.name }} - 
        Quantité: {{ article.quantite }} - 
        Sous-total: {{ article.sous_total }} €
    </li>
{% empty %}
    <li>Aucun article dans cette commande</li>
{% endfor %}
</ul>

<h3>Total de la commande : {{ panier.total_panier }} €</h3>

{% if commande_is_valide %}

<a href="{% url 'payement_app:choix-paiement' commande_detail.id %}"> choix du paiements</a>
<a href="{% url 'order_app:voir-panier' %}">← Retour au panier</a>

{% else %}
<a href="{% url 'order_app:valide-commande' %}">Validée votre commande pour passer au payement</a>-

<br>
<a href="{% url 'order_app:voir-panier' %}">← Retour au panier</a>
{% endif %}
    

src/templates/order_templates/historique_commande.html
<h1>Historique des commandes</h1>

{% for comande_story in   historique_commande  %}
    <h3>Commande du: {{ comande_story.date_commande}}</h3>
    <h3>Status: {{comande_story.statut}}</h3>
    <h3>Satuts Payement: {{comande_story.paiements.statu }} </h3>
    <h3>Total commande : {{ commde_story.Panier.total_panier }}</h3>
    <hr>
    <hr>
{% endfor %}
    

src/templates/order_templates/panier.html
<!-- EN HAUT du template -->
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

<h1>panier: {{ panier.status }}</h1>
<ul>
{% for article  in articles  %}
<li>
<h3>article : {{ article.product }}</h3>
    <h3>quantité: {{ article.quantite }}</h3>
     <a href="{% url 'order_app:modifier-article' article.id %} ">modifer la quantité</a>
     <a href="{% url 'order_app:supprimer-article' article.id %}">Supprimer l'article</a>
</li>
   
{% endfor %}
</ul>

<h1>total : {{ total }}</h1>


{% if commande %}
    <a href="{% url 'order_app:detail-commande' commande.id %}">detail de la commande ></a>
    <br>
    <a href="{% url 'order_app:valide-commande' %}">Validée commande</a>
    <br>
{% else %}
    <p>Ajoutez des articles pour créer une commande</p>
{% endif %}

<a href="{% url 'order_app:historique-commande' %}">Historique des commande </a>